# Generated by Django 3.0.7 on 2020-06-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hexanovate', '0003_subscriber_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='email_sent',
        ),
    ]
