# Generated by Django 3.0.7 on 2020-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_related_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='related_blogs',
            field=models.ManyToManyField(blank=True, related_name='related_blogs_reverse', to='blogs.Blog'),
        ),
    ]
