# Generated by Django 3.0.7 on 2020-06-18 06:47

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200613_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(upload_to=blogs.models.upload_image_path),
        ),
    ]
