# Generated by Django 3.0.7 on 2020-06-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexanovate', '0002_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
