# Generated by Django 3.0.7 on 2020-06-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hexanovate', '0004_remove_subscriber_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('guidance', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=11)),
                ('message', models.TextField()),
            ],
        ),
    ]
