# Generated by Django 3.0.7 on 2020-07-01 17:29

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0008_auto_20200620_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('thumbnail', models.ImageField(upload_to=resources.models.upload_image_path)),
                ('author', models.CharField(max_length=128)),
                ('short_description', models.TextField()),
                ('attachment', models.FileField(upload_to=resources.models.upload_resource_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='blogs.Category')),
            ],
        ),
    ]
