# Generated by Django 3.0.7 on 2020-06-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200610_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='related_blogs',
            field=models.ManyToManyField(blank=True, to='blogs.Blog'),
        ),
    ]
